### PR TITLE
ui: add templ components and docs

### PR DESCRIPTION
**Pull request by schogges**
Adds ui templ components and docs page. Initial set of components: `button`, `card` (compound component), `checkbox`, `drawer` (compound component), `h1`-`h3`, `hero`, `input`, `link`, `select`, `switch` and `textarea`. All components are based on [DaisyUI](https://daisyui.com/) (HTML/CSS only). The collection will be further extended and more details about the components will follow.

Screenshot 2024-08-10 at 20 27 39

Part of #96

### CODE REVIEW

**Review by frzifus — COMMENTED** [review]
Awesome! But ci failed. ^^

**Comment by schogges** [comment]
> Awesome! But ci failed. ^^

Yeah 😄 I have added the licensehead to `.templ` files but the check still fails. Looks like there is a pattern mismatch of what is checked in [licensecheck](https://github.com/quixsi/core/blob/main/Makefile#L70) and the head of templ generated `_templ.go` files. I could exclude them from `$ALL_GO_FILES` or rather don't put generated files into source control, wdyt?

**Comment by schogges** [comment]
I have removed the generated `_templ.go` files from source control. However, to make any checks like lint, the `*.go` files are required. Also when doing any checks locally, the `_templ.go` files may already exist. Therefore I have adjusted the check for licensehead and ci accordingly.

**Comment by led0nk** [comment]
Looks very good and offers a nice toolset! So i've read through the process and I think the way you handled the licenseheader recently is the best possible while ignoring the `_templ.go`-files.

Some additional things not belonging to this PR:

I'm not sure about handling the linting, maybe we should just add the `make generate` command to `make lint` since it's a common mistake?
On top of that, we should think about some kind of contribution command (e.g. `make contribute`), which includes the most important steps for testing (before CI).  
wdyt?

We should switch to stdlib soon, before it gets overloaded 😄

**Review by led0nk — APPROVED** [review]

**Comment by schogges** [comment]
> Looks very good and offers a nice toolset! So i've read through the process and I think the way you handled the licenseheader recently is the best possible while ignoring the `_templ.go`-files.
> 
> Some additional things not belonging to this PR:
> 
> I'm not sure about handling the linting, maybe we should just add the `make generate` command to `make lint` since it's a common mistake? On top of that, we should think about some kind of contribution command (e.g. `make contribute`), which includes the most important steps for testing (before CI). wdyt?
> 
> We should switch to stdlib soon, before it gets overloaded 😄

Thanks for your feedback ❤️ 
@frzifus, @miyunari and I had a discussion yesterday and compared the dis-/advantages of putting the generated _templ.go files into source control. We agreed that it makes sense to put them into source control because it's generally easier for further use because a project would not necessarily have to install templ itself but could directly make use of the components and we would immediately see changes in the output of templ generate in newer versions. The downside is just that there is more code/text checked in.

---

Regarding the contribution command, I think we could add some pre-commit hook that would run when committing something. Ideally only the staged stuff will be considered in there to keep them as fast as possible.

**Comment by led0nk** [comment]
> We agreed that it makes sense to put them into source control because it's generally easier for further use because a project would not necessarily have to install templ itself but could directly make use of the components and we would immediately see changes in the output of templ generate in newer versions. The downside is just that there is more code/text checked in.

That would result in including the generated `_templ.go` files for the licenseheader, am i correct?

**Comment by schogges** [comment]
> > We agreed that it makes sense to put them into source control because it's generally easier for further use because a project would not necessarily have to install templ itself but could directly make use of the components and we would immediately see changes in the output of templ generate in newer versions. The downside is just that there is more code/text checked in.
> 
> That would result in including the generated `_templ.go` files for the licenseheader, am i correct?

The licenseheaders are included in the generated output, but not matching the pattern and therefore I would just keep ignoring them during linting

**Pull request merged**
